name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Check Code Formatting
      run: cargo fmt -- --check
    - name: Check Clippy
      run: cargo clippy -- -D warnings
# TODO tests need consul environment
#    - name: Run tests
#      run: cargo test --verbose
